// # AUTOGEN FIND COMMANDS GENERATED by GoldPKG
// # AUTOGEN FIND PLEASE DO NOT MODIFY
// find_package(Catch2 CONFIG REQUIRED)
export const TARGET_CMAKE_REGEX = /^(#\s*AUTOGEN\s*TARGET*?|(target_.*?\(.*? .*?\)))/i;
export const FIND_CMAKE_REGEX = /^(#\s*AUTOGEN\s*FIND*?|(find_.*?\(.*? .*?\)))/i;

// project(SAMPLE-LIB-TESTS)
export const PROJECT_NAME_REGEX = /project\s*\(.*?\)*?/i;
export const ADD_CMAKE_REGEX = /^(#\s*AUTOGEN\s*ADD*?|(add_.*?\((.*?) .*? .*?\)))/i;

// set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/.vcpkg/scripts/buildsystems/vcpkg.cmake)
export const TOOLCHAIN_CMAKE_REGEX = /^\s*(#\s*AUTOGEN\s*TOOLCHAIN*?|set\s*\(\s*CMAKE_TOOLCHAIN_FILE*?\)*?)/i;

// cmake_minimum_required(
export const CMAKE_MINIMUM_CMAKE_REGEX = /^\s*cmake_minimum_required\s*\(*?\)*?/i;
