name: Publish to NPM
on:
    push:
        tags:
            - '*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - name: Cache node_modules
              id: cache-modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

            - name: Install
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install

            - run: npm run build

            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
